openapi: 3.0.3
info:
  title: Order Status Service API
  description: API to fetch the current status of an order
  version: 1.0.0

paths:
  /orders/{orderId}/status:
    get:
      summary: Fetch order status
      operationId: getOrderStatus
      parameters:
        - name: orderId
          in: path
          required: true
          description: Unique identifier of the order
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Order status fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatusResponse'
        '404':
          description: Order not found

components:
  schemas:
    OrderStatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'

    OrderStatus:
      type: string
      title: Order status
      enum:
        - PENDING
        - INITIATED
        - ACCEPTED
        - SHIPPED
        - DELIVERED
        - CANCELLED
